[server]
server_id = 1
http_port = 3000
database_driver = "mongodb"
rate_limit_minutes = 10
rate_limit_requests = 200
body_limit = "10kb"
static_path = "public"
environment = "development"  # server environment: development, staging, production

[server.views]
path = "views"
default_layout = "default_layout.hbs"
layouts_path = "views/layouts"
partials_path = "views/partials"

[server.platform]
user_roles = ["Guest", "client", "coach", "admin"]
platform_author_name = "miketerry.org"
platform_author_url = "https://miketerry.org"
support_email = "support@miketerry.org"
support_url = "https://local.mercury/support"
copyright = 2025

[server.session]
session_secret = "2ab976ae98b6a83ca401a8dd15fefdc193c2d4702e56ea1d5efdea4174407d69"

[server.session.redis]
host = "127.0.0.1"
port = 6379
password = ""                          # optional
prefix = "sess:"                       # optional

[server.log]
database_uri = "mongodb://localhost:27017/logs"
table_name = "logs"
expiration_days = 1
capped = false
max_size = 10
max_docs = 10000

[server.mail]
transport = "file"
template_path = "mail_templates"

[server.mail.file]
output_path= "mail_messages"

[server.mail.postmark]
api_key = "67d2044f-4927-47e0-8639-2859a1f97b97"

[server.mail.smtp]
host = "smtp.example.com"
port = 587
username = "username"
password = "password"

[server.mail.sendgrid]
api_key = ""

###############################################################
# Tenants
###############################################################

[[tenants]]
tenant_id = 1
name = "Development"
environment = "development"
server_node = 1
domain = "local.dev"
database_uri = "mongodb://localhost:27017/dev"
theme_mode = "lightMode"

[tenants.site]
title = "(development) Life Coaching"
slogan = "Red Hot Life Coaching"
tenant_owner = "Mercury Life Coaching, LLC"
coach_fullname = "Donald Duck"
coach_email = "donald.duck@mercurylifecoaching.com"
support_email = "support@mercurylifecoaching.com"
support_url = "https://local.mercury/support"

[tenants.views]
views_path = "tenants/dev/views"
layouts_path = "tenants/dev/views/layouts"
partials_path = "tenants/dev/views/partials"
default_layout = "dev_default_layout.hbs"

[tenants.assets]
logo_path = "assets/logos/dev_logo.png"
mail_templates_path = "tenants/dev/mail_templates"


[[tenants]]
tenant_id = 2
name = "Testing"
environment = "testing"
server_node = 1
domain = "local.test"
database_uri = "mongodb://localhost:27017/test"
theme_mode = "darkMode"

[tenants.site]
title = "(Test) Life Coaching"
slogan = "Quality, comprehensive life coaching for everyone"
tenant_owner = "Two Roads Movement, LLC"
coach_fullname = "Dylan Terry"
coach_email = "dylan.terry@tworoadsmovement.com"
support_email = "support@tworoadsmovement.com"
support_url = "https://www.tworoadsmovement.com/support"

[tenants.views]
views_path = "tenants/test/views"
layouts_path = "tenants/test/views/layouts"
partials_path = "tenants/test/views/partials"
default_layout = "test_default_layout.hbs"

[tenants.assets]
logo_path = "assets/logos/test_logo.png"
mail_templates_path = "tenants/test/mail_templates"


[[tenants]]
tenant_id = 3
name = "Staging"
environment = "staging"
server_node = 1
domain = "local.stage"
database_uri = "mongodb://localhost:27017/stage"
theme_mode = "lightMode"

[tenants.site]
title = "Two Roads Movement"
slogan = "Quality, comprehensive life coaching for everyone"
tenant_owner = "Two Roads Movement, LLC"
coach_fullname = "Dylan Terry"
coach_email = "dylan.terry@tworoadsmovement.com"
support_email = "support@tworoadsmovement.com"
support_url = "https://www.tworoadsmovement.com/support"

[tenants.views]
views_path = "tenants/stage/views"
layouts_path = "tenants/stage/views/layouts"
partials_path = "tenants/stage/views/partials"
default_layout = "stage_default_layout.hbs"

[tenants.assets]
logo_path = "assets/logos/stage_logo.png"
mail_templates_path = "tenants/stage/mail_templates"


[[tenants]]
tenant_id = 4
name = "Production"
environment = "production"
server_node = 1
domain = "local.prod"
database_uri = "mongodb://localhost:27017/prod"
theme_mode = "darkMode"

[tenants.site]
title = "Two Roads Movement"
slogan = "Quality, comprehensive life coaching for everyone"
tenant_owner = "Two Roads Movement, LLC"
coach_fullname = "Dylan Terry"
coach_email = "dylan.terry@tworoadsmovement.com"
support_email = "support@tworoadsmovement.com"
support_url = "https://www.tworoadsmovement.com/support"

[tenants.views]
views_path = "tenants/prod/views"
layouts_path = "tenants/prod/views/layouts"
partials_path = "tenants/prod/views/partials"
default_layout = "prod_default_layout.hbs"

[tenants.assets]
logo_path = "assets/logos/prod_logo.png"
mail_templates_path = "tenants/prod/mail_templates"
