
[server]
# server identifier for multi-server installation
server_id=1 
# port server listens on for http requests
http_port=3000
rate_limit_minutes = 10
rate_limit_requests = 200
body_limit = "10kb"
session_secret = "2ab976ae98b6a83ca401a8dd15fefdc193c2d4702e56ea1d5efdea4174407d69"
static_path = "public"
views_path = "views"
views_default_layout = "default_layout.hbs"
views_layouts_path = "views/layouts"
views_partials_path = "views/partials"

# redis session storage
[redis]
host = "127.0.0.1"
port = 6379
password = ""   # optional
prefix = "sess:" # optional

# logging
[log]
table_name = "logs"
expiration_days = 1
capped = false
max_size = 10
max_docs = 10000

# mail messages
[mail]
transport=file  # file, smtp, postmark
template_path=mail_templates
file_message_path=mail_messages
postmark_api_key="67d2044f-4927-47e0-8639-2859a1f97b97"

# ============================================================
# Tenant settings
# ============================================================

[[tenants]]
tenant_id=1
name = "development"
node = 1
mode = "development"
domain = "local.dev"
database_driver=mongodb
database_uri = "mongodb://localhost:27017/dev"
site_title = "(development) Life Coaching"
site_slogan = "Ret Hot Life Coaching"
site_coach_fullname = "Donald Duck"
site_coach_email = "donald.duck@mercurylifecoaching.com"
site_support_email = "support@miketerry.org"
site_support_url = "https://local.mercury/support"
site_owner = "Mercury Life Coaching, LLC"
site_author_name = "miketerry.org"
site_author_url = "https://miketerry.org"
site_copyright = 2025
site_roles = ["Guest", "client", "coach", "admin"]

[[tenants]]
tenant_id=2
name = "Testing"
node = 1
mode = "testing"
domain = "local.test"
database_driver=mongodb
database_uri = "mongodb://localhost:27017/test"
site_title = "(Test) Life Coaching"
site_slogan = "Quality, comprehensive life coaching for everyone"
site_coach_fullname = "Dylan Terry"
site_coach_email = "dylan.terry@tworoadsmovement.com"
site_support_email = "support@tworoadsmovement.com"
site_support_url = "https://www.tworoadsmovement.com/support"
site_owner = "Two Roads Movement, LLC"
site_author_name = "miketerry.org"
site_author_url = "https://miketerry.org"
site_copyright = 2025
site_roles = ["Guest", "client", "coach", "admin"]


[[tenants]]
tenant_id=3
name = "Staging"
node = 1
mode = "staging"
domain = "local.stage"
database_driver=mongodb
database_uri = "mongodb://localhost:27017/stage"
site_title = "Two Roads Movement"
site_slogan = "Quality, comprehensive life coaching for everyone"
site_coach_fullname = "Dylan Terry"
site_coach_email = "dylan.terry@tworoadsmovement.com"
site_support_email = "support@tworoadsmovement.com"
site_support_url = "https://www.tworoadsmovement.com/support"
site_owner = "Two Roads Movement, LLC"
site_author_name = "miketerry.org"
site_author_url = "https://miketerry.org"
site_copyright = 2025
site_roles = ["Guest", "client", "coach", "admin"]

[[tenants]]
tenant_id=4
name = "Production"
node = 1
mode = "Production"
domain = "local.prod"
database_driver=mongodb
database_uri = "mongodb://localhost:27017/prod"
site_title = "Two Roads Movement"
site_slogan = "Quality, comprehensive life coaching for everyone"
site_coach_fullname = "Dylan Terry"
site_coach_email = "dylan.terry@tworoadsmovement.com"
site_support_email = "support@tworoadsmovement.com"
site_support_url = "https://www.tworoadsmovement.com/support"
site_owner = "Two Roads Movement, LLC"
site_author_name = "miketerry.org"
site_author_url = "https://miketerry.org"
site_copyright = 2025
site_roles = ["Guest", "client", "coach", "admin"]
